name: Docs to Pages Static Site Generator

on:
  push:
  repository_dispatch:
    types: [google_docs_publish]
  workflow_dispatch:
  # schedule:
    # - cron: '0 * * * *'    # 毎時0分（毎時実行/必要に応じて変更）

permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOC_IDS_JSON: ${{ secrets.DOC_IDS_JSON }}
    steps:
      - name: チェックアウト
        uses: actions/checkout@v4

      - name: Node.js セットアップ
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 依存パッケージインストール
        run: |
          npm install node-fetch@2 cheerio

      - name: 静的サイト生成
        run: |
          node script/docs-to-pages.js

      - name: Add CNAME file
        run: echo 'jichiro.jpcenter.online' > public/CNAME

      - name: GitHub Pages デプロイ
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
